version: '3'
services:
    client:
      image: ss4net1/multi-client
      mem_limit: 128m
    server:
      image:ss4net1/multi-server
      mem_limit: 128m
    worker:
      image: ss4net1/multi-worker
      mem_limit: 128m
    nginx:
      image: ss4net1/multi-nginx
      ports:
        - "80:80"
